### PR TITLE
Support usage of MyBinder.org - fixes #2, #3

### LINKED ISSUE #2: plt.style.use('datastory') fails
The error...

```
OSError: 'datastory' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles
```

From running...

```
plt.style.use('datastory')
```

... can be resolved by:
```
plt.style.use('../assets/datastory.mpltstyle')
```

Notebook name | Status
-|-
2019-01-23-educational-levels.ipynb     | OK! (style if clause)
2019-01-30-parents-education.ipynb      | OK! (style if clause)
2019-02-06-income-inequality.ipynb      | OK! (style if clause)
2019-02-21-child-birth.ipynb            | OK! (style if clause)
2019-02-28-migration-word-counts.ipynb  | Issue #1
2019-03-08-female-mps.ipynb             | OK! (style if clause)
2019-03-14-squad.ipynb                  | fails on: `plt.style.use('datastory')`
2019-03-20-urbanization-africa.ipynb    | OK! (style if clause)
2019-04-04-no-friends.ipynb             | fails on: `plt.style.use('datastory')`
2019-04-10-state-budget.ipynb           | OK! (style if clause)
2019-04-25-age-of-leaders.ipynb         | OK! (style if clause)
2019-05-10-media-top-bottom.ipynb       | OK? No style used.

### LINKED ISSUE #3: Lacking support for mybinder.org
This repo could be fully runnable on mybinder.org with a single adjustment: add a `apt.txt` file with the content.

```
imagemagick
```

A mybinder.org badge should probably also be added to the README file, perhaps also with a note that it can be executed there without needing to install anything.

### PR DESCRIPTION
**Pull request by consideRatio**
:tada: :heart: I'm excited about what you have done and very happy that you have shared your code on GitHub! I'm keen on learning more about data visualization and your code is good inspiration. I also love the use of `imagemagick` to generate gifs!

## Background
This PR is a consequence of @salgo60 who made me spot [this tweet](https://twitter.com/e_Sundell/status/1119182617151201281) in my Twitter feed. Very happy and curious about what I saw I wanted to run the code myself.

MyBinder.org can help anyone run code from git repositories by constructing a custom Dockerfile that pre-installes a good foundation and adds everything needed to run the source code found in a git repository. But, mybinder.org, which is really a [BinderHub](https://github.com/jupyterhub/binderhub), which in turn relies on [repo2docker](https://github.com/jupyter/repo2docker), did not yet support installing Python dependencies from `Pipfile` at this time.

So, I set out to make a contribution to resolve that ([repo2docker#649](https://github.com/jupyter/repo2docker/pull/649)). With the help of @betatim to review and get it good enough for merge this support has now propagated to mybinder.org.

This makes this repo, with the small adjustment of adding a `apt.txt` file in it listing the `imagemagick` dependency runnable with a single click of a button.

## MyBinder.org buttons

__This is a button to run the code in my fork (this PR):__
[Binder](https://mybinder.org/v2/gh/consideratio/weekly-chart/mybinder-org-etc?urlpath=%2Flab%2Ftree%2Fnotebooks)

__This is a button to run the code in this repo's master branch:__
[Binder](https://mybinder.org/v2/gh/datastory-org/weekly-chart/master?urlpath=%2Flab%2Ftree%2Fnotebooks)

## What this PR does
So it is quite a mash of stuff, sorry for not making them separate PRs, I wanted to save some of my time. You can review the commits one by one to better understand what I've done if it seems messy from looking at the files changed section of this PR.

- 6bce75e - Fixes #3 by adding apt.txt containing `imagemagick`
- 2d79fbb - Fixes #2 by referencing a relative path, to `../assets/datastory.mpltstyle`.
- aa893fe
    - Added a mybinder.org badge
    - Wrote more explicit local installation instructions
    - Simplified the styling advice based on fix for #2

## Finally

@lapidus @miroli I'm hoping to be able to meet you in Stockholm tomorrow if that is possible!

Lots of appreciation for the work you have done!
/ Erik Sundell

### CODE REVIEW

**Comment by lapidus** [comment]
This is really nice @consideRatio. Thank you so much for the contribution. @miroli and I will assess the PR and add any comments. See you in Sthlm!

**Comment by miroli** [comment]
Thanks for the PR @consideRatio. Great stuff! This looks ready to be merged. Any additional comments @lapidus?

**Comment by consideRatio** [comment]
Your very welcome @miroli, thank you for all the work you do with datastory. It was inspiring to meet you @lapidus @miroli!

**Comment by consideRatio** [comment]
# Off topic to the PR
I wanted to ping the organizers of OpenHack Stockholm in November, as I think weekly-chart showcase excellent Jupyter notebooks and some realistic situations where data is consumed from external sources. OpenHack, meet Datastory btw ;)

Monika and @nikeh, this repo contains _Jupyter notebooks_ with code etc to generate the graphs (sometimes turned into gif animations), that are presented on https://datastory.org/sv/veckans-graf. This PR mostly added a button in markdown to the README.md of this repo. The button acting as a web link to mybinder.org with some passed details, allows this code to be runnable in a autogenerated docker container hosted on the cloud, using the free service without a need to login, meant to help make science reproducible etc.

__Try running the code yourself that generated the charts at datastory.org:__
[Binder](https://mybinder.org/v2/gh/consideratio/weekly-chart/mybinder-org-etc?urlpath=%2Flab%2Ftree%2Fnotebooks)

---

__GIF showing datastory.org's weekly chart__:
datajournalistik-datastory

**Comment by lapidus** [comment]
Thank you @consideRatio. Very nice to meet you!

**Pull request merged**
